name: Main Deployment

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-changes:

    runs-on: ubuntu-latest
    steps:
      - name: Update Assets Volume via Git Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_IP }}
          username: ${{ secrets.SERVER_HOST_USER }}
          key: ${{ secrets.SERVER_HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            REPO_DIR="${{ secrets.SERVER_REPO_LOCATION }}"
            REPO_NAME="${{ github.event.repository.name }}"
            REPO_URL="https://${{ secrets.SERVER_HOST_GITHUB_PAT }}@github.com/bkan0n/${{ github.event.repository.name }}.git"

            # Ensure base directory exists
            mkdir -p "$REPO_DIR"
            cd "$REPO_DIR"

            # Check if the repository exists
            if [ ! -d "$REPO_NAME/.git" ]; then
              echo "Repository not found. Cloning..."
              git clone "$REPO_URL" "$REPO_NAME"
            else
              echo "Repository exists. Pulling latest changes..."
              cd "$REPO_NAME"
              git pull origin main
            fi

            # Restart Docker services
            docker compose down >/dev/null
            doppler run -t ${{ secrets.DOPPLER_TOKEN }} -- docker compose up -d
