name: Main Deployment

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-changes:

    runs-on: ubuntu-latest
    steps:
      - name: Update Assets Volume via Git Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_IP }}
          username: ${{ secrets.SERVER_HOST_USER }}
          key: ${{ secrets.SERVER_HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.SERVER_REPO_LOCATION }}
            git pull https://${{secrets.SERVER_HOST_GITHUB_PAT}}@github.com/bkan0n/${{ github.event.repository.name }}.git main
            cd ${{ github.event.repository.name }} 
            echo ${{ secrets.DOPPLER_TOKEN }} | doppler configure set token --scope /
            docker compose down >/dev/null
            doppler run -- docker compose up -d
